config/routes.rb
Rails.application.routes.draw do
  # get 'home/index' was set by the controller
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to  "Dominic Davies", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to  "About", home_about_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Page</h1>
<p>Example text</p>

app/views/home/index.html.erb
<div class="jumbotron">
<div class="container">
  <h1 class="display-4">Ruby on Rails Rocks!</h1>
  <p class="lead">This is a simple website as it's been a long time since I have used Rails.</p>
  <hr class="my-4">
  <p>Tech used in this project</p>
  <ul>
  <li>Ruby on Rails 5.1</li>
  <li>Bootstrap 4.1</li>
  <li>Heroku</li>
  <br>
  <%= link_to  "About Me", home_about_path, class: "btn btn-danger btn-lg"  %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mysite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render  "home/navbar" %>
    <%= yield %>
  </body>
</html>